/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.controlador.Inventariobd;
import com.istloja.modelTables.ModelTableInventario;

/**
 *
 * @author jpsolanoc
 */
public class BusquedaAvanzada extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaAvanzada
     */
    private ModelTableInventario modelTableInventario;
    private Inventariobd controladorInventario;
    public BusquedaAvanzada(java.awt.Frame parent, boolean modal,ModelTableInventario modelTableInventario,Inventariobd controladorInventario) {
        super(parent, modal);
        this.modelTableInventario = modelTableInventario;
        this.controladorInventario = controladorInventario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        comboBoxInventarioBusqueda = new javax.swing.JComboBox<>();
        txtInventarioBusqueda = new javax.swing.JTextField();
        btnInventaripBusqueda = new javax.swing.JButton();
        tblInventario = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Avanzada Productos");

        jLabel14.setText("Busqueda");

        comboBoxInventarioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo Producto", "Descripcion" }));

        btnInventaripBusqueda.setText("Buscar");
        btnInventaripBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventaripBusquedaActionPerformed(evt);
            }
        });

        jTable1.setModel(modelTableInventario);
        tblInventario.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1172, Short.MAX_VALUE)
                .addComponent(btnInventaripBusqueda)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(comboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnInventaripBusqueda)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(comboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addComponent(tblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventaripBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventaripBusquedaActionPerformed
        // TODO add your handling code here:
        System.out.println("Combo" + comboBoxInventarioBusqueda.getSelectedIndex());
        switch (comboBoxInventarioBusqueda.getSelectedIndex()) {
            case 0://Codigo
            modelTableInventario.setInventarios(controladorInventario.ObtenerCodigo_pro(txtInventarioBusqueda.getText()));
            modelTableInventario.fireTableDataChanged();
            break;
            case 1://7Descripcion
            modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventarioDescripcion(txtInventarioBusqueda.getText()));
            modelTableInventario.fireTableDataChanged();
            break;
        }
    }//GEN-LAST:event_btnInventaripBusquedaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventaripBusqueda;
    private javax.swing.JComboBox<String> comboBoxInventarioBusqueda;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblInventario;
    private javax.swing.JTextField txtInventarioBusqueda;
    // End of variables declaration//GEN-END:variables
}
